Add support for modprobe and insmod
If the .ko file isn't found locally, attempt to modprobe
it.  This way the script can be reused in cases where
the module is built and installed in the modle library dirs.

diff --git a/aesd-char-driver/aesdchar_load b/aesd-char-driver/aesdchar_load
--- a/aesd-char-driver/aesdchar_load
+++ b/aesd-char-driver/aesdchar_load
@@ -11,7 +11,13 @@ else
     group="wheel"
 fi
 
-insmod ./$module.ko $* || exit 1
+if [ -e ${module}.ko ]; then
+    echo "Loading local built file ${module}.ko"
+    insmod ./$module.ko $* || exit 1
+else
+    echo "Local file ${module}.ko not found, attempting to modprobe"
+    modprobe ${module} || exit 1
+fi
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 rm -f /dev/${device}
 mknod /dev/${device} c $major 0
